<template>
  <div class="absolute" />
  <div class="relative" />
  <div class="inline" />

  <div class="fixed" />
  <div class="flex" />
  <div class="bottom-0 top-0 left-0 right-0" />
  <div class="bottom-1 top-1 left-1 right-1" />
  <div class="bottom-2 top-2 left-2 right-2" />
  <div class="bottom-3 top-3 left-3 right-3" />
  <div class="bottom-4 top-4 left-4 right-4" />
  <div class="bottom-8 top-8 left-8 right-8" />
  <div class="capitalize content-around cursor-pointer border-red-1" />

  <div class="rounded-none" />
  <div class="rounded-sm" />
  <div class="rounded" />
  <div class="rounded-md" />
  <div class="rounded-lg" />
  <div class="rounded-xl" />
  <div class="rounded-2xl" />
  <div class="rounded-3xl" />
  <div class="rounded-full" />
  <div class="rounded-t-none" />
  <div class="rounded-t-sm" />
  <div class="rounded-t" />
  <div class="rounded-t-md" />
  <div class="rounded-t-lg" />
  <div class="rounded-t-xl" />
  <div class="rounded-t-2xl" />
  <div class="rounded-t-3xl" />
  <div class="rounded-t-full" />
  <div class="rounded-r-none" />
  <div class="rounded-r-sm" />
  <div class="rounded-r" />
  <div class="rounded-r-md" />
  <div class="rounded-r-lg" />
  <div class="rounded-r-xl" />
  <div class="rounded-r-2xl" />
  <div class="rounded-r-3xl" />
  <div class="rounded-r-full" />
  <div class="rounded-b-none" />
  <div class="rounded-b-sm" />
  <div class="rounded-b" />
  <div class="rounded-b-md" />
  <div class="rounded-b-lg" />
  <div class="rounded-b-xl" />
  <div class="rounded-b-2xl" />
  <div class="rounded-b-3xl" />
  <div class="rounded-b-full" />
  <div class="rounded-l-none" />
  <div class="rounded-l-sm" />
  <div class="rounded-l" />
  <div class="rounded-l-md" />
  <div class="rounded-l-lg" />
  <div class="rounded-l-xl" />
  <div class="rounded-l-2xl" />
  <div class="rounded-l-3xl" />
  <div class="rounded-l-full" />
  <div class="rounded-tl-none" />
  <div class="rounded-tl-sm" />
  <div class="rounded-tl" />
  <div class="rounded-tl-md" />
  <div class="rounded-tl-lg" />
  <div class="rounded-tl-xl" />
  <div class="rounded-tl-2xl" />
  <div class="rounded-tl-3xl" />
  <div class="rounded-tl-full" />
  <div class="rounded-tr-none" />
  <div class="rounded-tr-sm" />
  <div class="rounded-tr" />
  <div class="rounded-tr-md" />
  <div class="rounded-tr-lg" />
  <div class="rounded-tr-xl" />
  <div class="rounded-tr-2xl" />
  <div class="rounded-tr-3xl" />
  <div class="rounded-tr-full" />
  <div class="rounded-br-none" />
  <div class="rounded-br-sm" />
  <div class="rounded-br" />
  <div class="rounded-br-md" />
  <div class="rounded-br-lg" />
  <div class="rounded-br-xl" />
  <div class="rounded-br-2xl" />
  <div class="rounded-br-3xl" />
  <div class="rounded-br-full" />
  <div class="rounded-bl-none" />
  <div class="rounded-bl-sm" />
  <div class="rounded-bl" />
  <div class="rounded-bl-md" />
  <div class="rounded-bl-lg" />
  <div class="rounded-bl-xl" />
  <div class="rounded-bl-2xl" />
  <div class="rounded-bl-3xl" />
  <div class="rounded-bl-full" />

  <div class="drop-shadow-sm" />
  <div class="drop-shadow" />
  <div class="drop-shadow-md" />
  <div class="drop-shadow-lg" />
  <div class="drop-shadow-xl" />
  <div class="drop-shadow-2xl" />
  <div class="drop-shadow-none" />

  <div class="bg-white" />
  <div class="bg-white/90" />
  <div class="bg-white/80" />
  <div class="bg-white/70" />
  <div class="bg-white/50" />
  <div class="bg-white/40" />
  <div class="bg-white/30" />
  <div class="bg-white/20" />
  <div class="bg-white/10" />
  <div class="bg-white/5" />

  <div class="bg-black" />
  <div class="bg-black/90" />
  <div class="bg-black/80" />
  <div class="bg-black/70" />
  <div class="bg-black/50" />
  <div class="bg-black/40" />
  <div class="bg-black/30" />
  <div class="bg-black/20" />
  <div class="bg-black/10" />
  <div class="bg-black/5" />

  <div class="text-gray-900" />
  <div class="text-gray-800" />
  <div class="text-gray-700" />
  <div class="text-gray-600" />
  <div class="text-gray-500" />
  <div class="text-gray-400" />
  <div class="text-gray-300" />
  <div class="text-gray-200" />
  <div class="text-gray-100" />
  <div class="text-gray-50" />

  <div class="mx-auto" />
  <div class="m-1" />
  <div class="m-2" />
  <div class="m-4" />
  <div class="m-8" />

  <div class="grid" />
  <div class="grid-cols-1" />
  <div class="grid-cols-2" />
  <div class="grid-cols-3" />
  <div class="grid-cols-4" />
  <div class="grid-cols-5" />
  <div class="grid-cols-6" />
  <div class="grid-cols-7" />
  <div class="grid-cols-8" />

  <div class="grid-row-1" />
  <div class="grid-row-2" />
  <div class="grid-row-3" />
  <div class="grid-row-4" />
  <div class="grid-row-5" />
  <div class="grid-row-6" />
  <div class="grid-row-7" />
  <div class="grid-row-8" />

  <div class="col-span-1" />
  <div class="col-span-2" />
  <div class="col-span-3" />
  <div class="col-span-4" />
  <div class="col-span-5" />
  <div class="col-span-6" />
  <div class="col-span-7" />
  <div class="col-span-8" />

  <div class="row-span-1" />
  <div class="row-span-2" />
  <div class="row-span-3" />
  <div class="row-span-4" />
  <div class="row-span-5" />
  <div class="row-span-6" />
  <div class="row-span-7" />
  <div class="row-span-8" />

  <div class="gap-1" />
  <div class="gap-2" />
  <div class="gap-3" />
  <div class="gap-4" />
  <div class="gap-5" />
  <div class="gap-6" />
  <div class="gap-7" />
  <div class="gap-8" />

  <div class="w-full h-full" />

  <div class="text-center" />
  <div class="text-xl" />
  <div class="text-2xl" />
  <div class="text-sm italic" />


  <div class="font-light" />
  <div class="font-bold" />
</template>
